# Generated by Django 4.2.2 on 2023-07-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booksAPI", "0002_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.ManyToManyField(
                default=1, related_name="books", to="booksAPI.category"
            ),
        ),
    ]
