# Generated by Django 4.2.2 on 2023-07-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booksAPI", "0003_alter_category_options_book_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.ManyToManyField(related_name="books", to="booksAPI.category"),
        ),
    ]
